name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 */2 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: BossBele/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: "00d824be45539140c582aec64dac9624"
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
